---
name: Prepare releases
run-name: Prepare_releases
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: python3.12
    steps:
      - name: Clone repository
        uses: https://git.dryusdan.fr/actions/checkout@v4
      - name: Deploy new package on repository
        if: gitea.event_name != 'pull_request'
        run: |
          poetry config virtualenvs.create false
          poetry source add --priority=supplemental forgejo https://git.dryusdan.fr/api/packages/Dryusdan/pypi
          poetry config http-basic.forgejo ${{ secrets.REPOSITORY_USER }} ${{ secrets.REPOSITORY_TOKEN }}
          poetry publish --build --repository forgejo
